import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
// 1. Critical import so Tailwind and daisyUI load on every page
import "./globals.css"; 
import Navbar from "./Componenet/Nav";
import Footer from "./Componenet/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-base-200 text-base-content">
        
        <Navbar/>
        

        {/* Dynamic Inner Layout Frame */}
        <main className="flex-1 w-full">
          {children}
        </main>
    <Footer></Footer>
      </body>
    </html>
  );
}